spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/demotry/protocol/openid-connect/certs
